<explicitPathName>$explicitPathName</explicitPathName>
<foreach_explicitPathHopsList>
	<explicitPathHops>
		<foreach_explicitPathHop>
			<explicitPathHop>
				<mplsTunnelHopIndex>$mplsTunnelHopIndex</mplsTunnelHopIndex>
				<mplsTunnelHopType>includeStrict</mplsTunnelHopType>
				<mplsTunnelHopIntType>default</mplsTunnelHopIntType>
				<mplsTunnelHopAddrType>IPV4</mplsTunnelHopAddrType>
				<mplsTunnelHopIpAddr>$mplsTunnelHopIpAddr</mplsTunnelHopIpAddr>
			</explicitPathHop>
		</foreach_explicitPathHop>
	</explicitPathHops>
</foreach_explicitPathHopsList>