<flows>
<foreach_flowList>
	<flow> 
        <name>$instanceName</name>  
		<identifyIndex>$pwId</identifyIndex>
		<desIp>$peerIp</desIp>
		<policy>$policy</policy>
		<isDouleConfig></isDouleConfig>
		<interfaceName>$interfaceName</interfaceName>
	</flow>
</foreach_flowList>
</flows>